# Generated by Django 5.2 on 2025-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.CharField(default='Unknown Cuisine', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.CharField(default='Unnamed Dish', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
